<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Azka.Domain\Azka.Domain.csproj" />
    <ProjectReference Include="..\Azka.Services\Azka.Services.csproj" />
    <ProjectReference Include="..\Azka.Services.DTOs\Azka.Services.DTOs.csproj" />
    <ProjectReference Include="..\Azka.Services.Interfaces\Azka.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Azka.Persistence\Azka.Persistence.csproj" />
    <ProjectReference Include="..\Azka.Shared\Azka.Shared.csproj" />
  </ItemGroup>
</Project>
